services:
  frontend:
    build: ./frontend
    ports:
      - '4200:80'
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    networks:
      - app-network
    # volumes: # Uncomment for development
    #   - ./backend:/app
    # command: npm run start:dev

  postgres:
    image: postgres:latest
    env_file:
      - ./backend/.env
    ports:
      - '5432:5432'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
