version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - '4200:80'
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/whale-db
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: whale-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password # get from env
    ports:
      - '5432:5432'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
